// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCONxYJJZd6IP00tvqKVb7Jys3qhxajxmQ',
    appId: '1:101188174074:web:9d7ecb6e386136c9d18943',
    messagingSenderId: '101188174074',
    projectId: 'message-board-app-4e893',
    authDomain: 'message-board-app-4e893.firebaseapp.com',
    storageBucket: 'message-board-app-4e893.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFzFxfJtAu09wXyfvBNmz_bPX-JGdROHY',
    appId: '1:101188174074:android:4acbc52d30a64ee0d18943',
    messagingSenderId: '101188174074',
    projectId: 'message-board-app-4e893',
    storageBucket: 'message-board-app-4e893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsbhH1hQUYn4qyjxKtYT945atcfyK-edo',
    appId: '1:101188174074:ios:65efb58781470b7cd18943',
    messagingSenderId: '101188174074',
    projectId: 'message-board-app-4e893',
    storageBucket: 'message-board-app-4e893.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsbhH1hQUYn4qyjxKtYT945atcfyK-edo',
    appId: '1:101188174074:ios:65efb58781470b7cd18943',
    messagingSenderId: '101188174074',
    projectId: 'message-board-app-4e893',
    storageBucket: 'message-board-app-4e893.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCONxYJJZd6IP00tvqKVb7Jys3qhxajxmQ',
    appId: '1:101188174074:web:ce63bfaa6960fd53d18943',
    messagingSenderId: '101188174074',
    projectId: 'message-board-app-4e893',
    authDomain: 'message-board-app-4e893.firebaseapp.com',
    storageBucket: 'message-board-app-4e893.firebasestorage.app',
  );

}